"""empty message

Revision ID: 3a1926b10553
Revises: 1da6723d89bf
Create Date: 2021-03-20 19:00:48.278164

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a1926b10553'
down_revision = '1da6723d89bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users_info', sa.Column('gender', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users_info', 'gender')
    # ### end Alembic commands ###
