"""empty message

Revision ID: 3c808e66cc65
Revises: 80d2fbbc5f09
Create Date: 2021-03-19 00:12:09.874811

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c808e66cc65'
down_revision = '80d2fbbc5f09'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('categories', 'destroy')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('destroy', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
