"""empty message

Revision ID: 407bda929512
Revises: 6339ea2887f3
Create Date: 2021-03-20 12:34:59.595201

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '407bda929512'
down_revision = '6339ea2887f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users_info')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users_info',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('age', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('creation_date', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('job', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('company', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('city', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='users_info_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='users_info_pkey')
    )
    # ### end Alembic commands ###
