"""empty message

Revision ID: 48f7630a9da0
Revises: eb1a39763fe9
Create Date: 2021-03-20 17:42:53.899243

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48f7630a9da0'
down_revision = 'eb1a39763fe9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users_info', 'creation_date',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_unique_constraint(None, 'users_info', ['user_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users_info', type_='unique')
    op.alter_column('users_info', 'creation_date',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
