"""empty message

Revision ID: 4b18a50e0c86
Revises: ced2d2e35762
Create Date: 2021-03-20 18:37:13.875383

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b18a50e0c86'
down_revision = 'ced2d2e35762'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users_info', 'creation_date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users_info', sa.Column('creation_date', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
