"""empty message

Revision ID: ea0cf7f08843
Revises: 407bda929512
Create Date: 2021-03-20 12:40:05.622894

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea0cf7f08843'
down_revision = '407bda929512'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('creation_date', sa.Integer(), nullable=False),
    sa.Column('job', sa.String(), nullable=False),
    sa.Column('company', sa.String(), nullable=False),
    sa.Column('city', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users_info')
    # ### end Alembic commands ###
