"""empty message

Revision ID: eb1a39763fe9
Revises: ea0cf7f08843
Create Date: 2021-03-20 17:04:00.625212

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb1a39763fe9'
down_revision = 'ea0cf7f08843'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users_info', 'creation_date',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users_info', 'creation_date',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
